[tool.ruff]
line-length = 88
target-version = "py311"
exclude = ["migrations", ".venv", "venv", "__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "DJ"]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
docstring-code-format = true
