# Generated by Django 5.2.3 on 2025-06-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='category_id',
            new_name='category',
        ),
    ]
